# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [4]:
import numpy as np
arr = np.random.uniform(0, 20, (4, 7))
arr

array([[ 9.3264341 , 18.15687442,  0.52202983,  2.11620972, 14.17833816,
        18.82534394, 11.62750764],
       [ 8.1409898 ,  0.13364509, 12.03318102, 12.24934027,  0.63637359,
         9.47820473,  9.27834982],
       [ 8.66632948, 16.88381764, 17.55872373, 13.89683877, 15.23561878,
         9.52472824, 19.17549221],
       [16.44255412, 18.91562488,  2.57757122,  4.34340989, 12.44723819,
         5.84909445,  6.96377075]])

Нормализация:

In [5]:
arr_new = (arr - arr.min()) / (arr.max() - arr.min())
arr_new

array([[0.48276771, 0.94650636, 0.02039638, 0.10411619, 0.73756989,
        0.98161164, 0.60361069],
       [0.42051302, 0.        , 0.624915  , 0.6362668 , 0.02640125,
        0.49073809, 0.48024252],
       [0.44810172, 0.87965062, 0.91509393, 0.72278669, 0.79309395,
        0.49318131, 1.        ],
       [0.85647726, 0.98635283, 0.12834501, 0.22107965, 0.64665959,
        0.30015205, 0.35869029]])

2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [8]:
matrix = np.random.randint(0, 10, size=(8,10))
summ = np.sum(matrix, axis = 1)
index = np.where(summ == min(summ))
matrix, summ, index, matrix[index]

(array([[8, 2, 4, 1, 0, 8, 2, 6, 8, 2],
        [8, 7, 2, 2, 5, 2, 8, 8, 3, 6],
        [6, 2, 8, 1, 5, 6, 7, 8, 9, 5],
        [4, 9, 8, 4, 3, 9, 9, 0, 8, 5],
        [4, 4, 1, 0, 0, 3, 5, 8, 1, 7],
        [2, 1, 7, 8, 7, 1, 5, 3, 1, 2],
        [0, 3, 1, 7, 5, 8, 5, 0, 1, 5],
        [9, 9, 8, 6, 8, 6, 6, 2, 7, 1]]),
 array([41, 51, 57, 59, 33, 37, 35, 62]),
 (array([4], dtype=int64),),
 array([[4, 4, 1, 0, 0, 3, 5, 8, 1, 7]]))

3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

In [9]:
a = np.array([0, 0, 0, 30])
b = np.array([50, 40, 0, 10])
sum((a-b)**2)**0.5

67.08203932499369

4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

In [10]:
A = np.matrix(
    [[-1, 2, 4], 
     [-3, 1, 2], 
     [-3, 0, 1]])

B = np.matrix(
    [[3, -1], 
     [2, 1]])

C = np.matrix(
    [[7, 21], 
     [11, 8], 
     [8, 4]])
x = np.linalg.inv(A)*(-C)*np.linalg.inv(B)
x

matrix([[ 1.00000000e+00,  5.32907052e-16],
        [-2.00000000e+00,  1.00000000e+00],
        [ 3.00000000e+00, -4.00000000e+00]])

## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [13]:
data = np.loadtxt('minutes_n_ingredients.csv', dtype=np.int32, delimiter=',', skiprows=1)
data[:5, :]

FileNotFoundError: minutes_n_ingredients.csv not found.

2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [14]:
for i in range(1, data.shape[1]):
    print(f'#{i}: min = {data[i].min()} max = {data[i].max()}, mean = {data[i].mean()}')

NameError: name 'data' is not defined

3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [ ]:
quantile_75 = np.quantile(data[:, 1], 0.75)
new_data = data[np.where(data[:, 1] <= quantile_75)[0], :]
new_data, new_data.shape

4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

5. Посчитайте, сколько уникальных рецептов находится в датасете.

6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

10. Выберите случайным образом и выведите информацию о 10 различных рецептах

11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

13. Выведите процент "простых" рецептов в датасете

14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.